meta_product_name: "Cigogn"
meta_title: "Cigogn - Trouvez le nom de votre bébé à deux n'a jamais été aussi simple "
meta_description: "Avec Cigogn, trouvez le prénom de votre futur bébé. L'application permet aux futurs parents de découvrir des centaines de noms et d'informations leur étant associées. Connectez votre compte à celui de votre partenaire, filtrez les prénoms selon vos préférences et commencez à swiper ! Dès que vous aimez tous les deux le même prénom, il s'ajoute à votre liste de matchs."
meta_type: "website"
meta_url: "www.cigogn.com"
meta_image: "meta_image.png" # should exist in `app/assets/images/